# Generated by Django 2.0.5 on 2018-05-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_products_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightSaper',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='article.Products')),
                ('lightshaper_id', models.AutoField(primary_key=True, serialize=False)),
                ('lightshaper_name', models.CharField(max_length=250)),
            ],
            bases=('article.products',),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('Állvány', 'Állvány'), ('Vaku', 'Vaku'), ('Fényformáló', 'Fényformáló'), ('Szett', 'Szett')], default='Állvány', max_length=250),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type_cat',
            field=models.CharField(blank=True, choices=[('Állvány', (('Földi', 'Földi'), ('Basic', 'Basic'), ('Boom', 'Boom'))), ('Vaku', (('Canon', 'Canon'), ('Nikon', 'Nikon'))), ('Fényformáló', (('Canon', 'Canon'), ('Nikon', 'Nikon')))], max_length=250),
        ),
    ]
