# Generated by Django 2.0.5 on 2018-05-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180519_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightsaper',
            name='lightshaper_id',
        ),
        migrations.RemoveField(
            model_name='lightsaper',
            name='lightshaper_name',
        ),
        migrations.AlterField(
            model_name='lightsaper',
            name='products_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.Products'),
        ),
    ]
