# Generated by Django 2.0.5 on 2018-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180519_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightShaper',
            fields=[
                ('lightshaper_id', models.AutoField(primary_key=True, serialize=False)),
                ('lightshaper_name', models.CharField(max_length=250)),
            ],
        ),        
        migrations.DeleteModel(
            name='LightSaper',
        ),
    ]
