# Generated by Django 2.0.5 on 2018-05-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180520_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('product_type', models.CharField(choices=[('Állvány', 'Állvány'), ('Vaku', 'Vaku'), ('Fényformáló', 'Fényformáló'), ('Szett', 'Szett')], default='Állvány', max_length=250)),
                ('product_type_cat', models.CharField(blank=True, choices=[('Állvány', (('Földi', 'Földi'), ('Basic', 'Basic'), ('Boom', 'Boom'))), ('Vaku', (('Canon', 'Canon'), ('Nikon', 'Nikon'))), ('Fényformáló', ((1, '60x90-es oktobox'), (2, '120-as parabolabox'), (3, '40x180-as softbox')))], max_length=250)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_product',
            field=models.ManyToManyField(to='article.Product'),
        ),
    ]
