# Generated by Django 2.0.5 on 2018-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180520_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type_cat',
            field=models.CharField(blank=True, choices=[('Állvány', (('Földi', 'Földi'), ('Basic', 'Basic'), ('Boom', 'Boom'))), ('Vaku', (('Canon', 'Canon'), ('Nikon', 'Nikon')))], max_length=250),
        ),
    ]
