# Generated by Django 2.0.5 on 2018-05-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180521_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_lightshaper',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='article.LightShaper'),
        ),
    ]
