# Generated by Django 2.0.5 on 2018-05-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_article_lightshaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_lightshaper',
        ),
        migrations.AddField(
            model_name='lightshaper',
            name='lightshaper_article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
    ]
