# Generated by Django 2.0.5 on 2018-05-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20180521_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_lightshaper',
        ),
        migrations.AddField(
            model_name='article',
            name='article_lightshaper',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='article.LightShaper'),
        ),
    ]
