# Generated by Django 2.0.5 on 2018-05-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20180521_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_lightshaper',
        ),
        migrations.AddField(
            model_name='article',
            name='article_lightshaper',
            field=models.ManyToManyField(to='article.LightShaper'),
        ),
    ]
