# Generated by Django 2.0.5 on 2018-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20180521_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_product',
            field=models.ManyToManyField(to='article.Product'),
        ),
    ]
