# Generated by Django 2.0.5 on 2018-05-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20180521_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='bundle_heading',
            new_name='bundle_title',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='bundle_body',
        ),
        migrations.AddField(
            model_name='bundle',
            name='bundle_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Állvány', 'Állvány'), ('Vaku', 'Vaku'), ('Slider', 'Slider'), ('Szett', 'Szett'), ('Fénymérő', 'Fénymérő')], default='Állvány', max_length=250),
        ),
    ]
