# Generated by Django 2.0.5 on 2018-05-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20180521_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='bundle_body',
            field=models.TextField(default=None),
        ),
    ]
