# Generated by Django 2.0.5 on 2018-05-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_bundle_bundle_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItems',
            fields=[
                ('rental_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_item_name', models.CharField(max_length=250)),
                ('rental_item_quantity', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='article.RentalItems'),
        ),
    ]
