# Generated by Django 2.0.5 on 2018-05-21 18:54

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('article', '0018_auto_20180521_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalItems',
            new_name='RentalItem',
        ),
    ]
