# Generated by Django 2.0.5 on 2018-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20180521_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rental_item',
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_item',
            field=models.ManyToManyField(to='article.RentalItem'),
        ),
    ]
