# Generated by Django 2.0.5 on 2018-05-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20180521_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rental_item',
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='article.RentalItem'),
        ),
    ]
