# Generated by Django 2.0.5 on 2018-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_remove_rentalitem_rental_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rent_product',
        ),
        migrations.AlterField(
            model_name='rental',
            name='user_name',
            field=models.CharField(max_length=250, verbose_name='Megrendelő neve: '),
        ),
    ]
