# Generated by Django 2.0.5 on 2018-05-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_auto_20180521_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rent_title',
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='rentel_item_type',
            field=models.CharField(choices=[('Fényformáló', 'Fényformáló'), ('Szett', 'Szett'), ('Termék', 'Termék')], default='Szett', max_length=250, verbose_name='Termék típusa'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='bundle_body',
            field=models.TextField(default=None, verbose_name='Szett tartalma'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='bundle_price',
            field=models.IntegerField(default=0, verbose_name='Szett ár'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='bundle_title',
            field=models.CharField(max_length=250, verbose_name='Szett neve'),
        ),
        migrations.AlterField(
            model_name='lightshaper',
            name='lightshaper_name',
            field=models.CharField(max_length=250, verbose_name='Fényformáló neve'),
        ),
        migrations.AlterField(
            model_name='lightshaper',
            name='lightshaper_price',
            field=models.IntegerField(default=0, verbose_name='Fényformáló ár'),
        ),
        migrations.AlterField(
            model_name='lightshaper',
            name='lightshaper_quantity',
            field=models.IntegerField(default=0, verbose_name='Fényformáló darab'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=250, verbose_name='Termék neve'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(verbose_name='Termék ár'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(verbose_name='Termék darabszám'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Állvány', 'Állvány'), ('Vaku', 'Vaku'), ('Slider', 'Slider'), ('Szett', 'Szett'), ('Fénymérő', 'Fénymérő')], default='Állvány', max_length=250, verbose_name='Termék típusa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type_cat',
            field=models.CharField(blank=True, choices=[('Állvány', (('Földi', 'Földi'), ('Basic', 'Basic'), ('Boom', 'Boom'))), ('Vaku', (('Canon', 'Canon'), ('Nikon', 'Nikon')))], max_length=250, verbose_name='Termék típus kategória'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_end',
            field=models.DateField(verbose_name='Bérlés vége'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_register',
            field=models.CharField(max_length=250, verbose_name='Bérlést felvette'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_start',
            field=models.DateField(verbose_name='Bérlés kezdete'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user_name',
            field=models.CharField(max_length=250, verbose_name='Bérlő neve'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user_phone',
            field=models.IntegerField(verbose_name='Bérlő telefonszáma'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='rental_item_quantity',
            field=models.CharField(max_length=250, verbose_name='darabszám'),
        ),
    ]
