# Generated by Django 2.0.5 on 2018-05-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_auto_20180521_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='rental_item_quantity',
            field=models.IntegerField(verbose_name='darabszám'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='rentel_item_type',
            field=models.CharField(choices=[('-------', '-------'), ('Fényformáló', 'Fényformáló'), ('Szett', 'Szett'), ('Termék', 'Termék')], default='-------', max_length=250, verbose_name='Termék típusa'),
        ),
    ]
