# Generated by Django 2.0.5 on 2018-05-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_auto_20180521_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='rental_item_bundle',
            field=models.ManyToManyField(blank=True, to='article.Bundle'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='rental_item_lightshaper',
            field=models.ManyToManyField(blank=True, to='article.LightShaper'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='rental_item_product',
            field=models.ManyToManyField(blank=True, to='article.Product'),
        ),
    ]
