# Generated by Django 2.0.5 on 2018-05-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_auto_20180522_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='rental',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='article.Rental'),
        ),
    ]
