# Generated by Django 2.1.dev20180514000620 on 2018-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_auto_20180522_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='rentalitem',
            unique_together={('rental', 'rental_item_id')},
        ),
    ]
