# Generated by Django 2.1.dev20180514000620 on 2018-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20180606_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='Visszahozva'),
        ),
    ]
